- include: sys_deps.yml

# Install arm if it doesn't exist.
- include: arm.yml
  when: armgcc.stdout == ""

# If apt-get install for arm fails, install manually.
- include: arm_manual.yml
  when: armgcc_manual.stdout == ""
